Web Programlama Donem Odevi/WebApplication4/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class UyeController : Controller
    {
        public ActionResult Cikis()
        {
            Session["KullanıcıAdı"] = null;
            RedirectToAction("Index", "Home");
            return View();
        }


        public ActionResult Giris()
        {
            DateTime Zaman = DateTime.Now;
            ViewBag.Tarih = Zaman;
            return View();
        }
        [HttpPost]
        public ActionResult Giris(Uye uye)
        {
            var kullanici = db.Uye.FirstOrDefault(x => x.KullanıcıAdı == uye.KullanıcıAdı && x.Sifre == uye.Sifre);
            var Admin = db.Uye.FirstOrDefault(x => x.AdminMi == uye.AdminMi);
            if (kullanici != null)
            {
                Session["KullanıcıAdı"] = kullanici;
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Hata = WebApplication4.Resources.lang.LoginError;
            return View();
        }
        private DbModels db = new DbModels();


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web Programlama Donem Odevi/WebApplication4/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@WebApplication4.Resources.lang.Metin2</title>
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/business-casual.css" rel="stylesheet">
</head>
<body>
    @Html.Partial("_header")
    @RenderBody()
    @Html.Partial("_footer")
</body>
</html>

Web Programlama Donem Odevi/WebApplication4/Views/Shared/_footer.cshtml
<footer class="footer text-faded text-center py-5">
    <div class="container">
        <h2><u>@WebApplication4.Resources.lang.Language </u></h2>
        <br />
        <ul class="navbar-nav mx-auto">
            <li>@Html.ActionLink("Türkçe", "ChangeCulture", "Home", new { lang = "tr", returnurl = this.Request.RawUrl }, null)</li>
            <li>@Html.ActionLink("Engilish", "ChangeCulture", "Home", new { lang = "en", returnurl = this.Request.RawUrl }, null)</li>
            <li>@Html.ActionLink("العربية", "ChangeCulture", "Home", new { lang = "ar", returnurl = this.Request.RawUrl }, null)</li>
        </ul>
    </div>
</footer>

Web Programlama Donem Odevi/WebApplication4/Views/Shared/_header.cshtml
<h1 class="site-heading text-center text-white d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3">@WebApplication4.Resources.lang.Welcome</span>
</h1>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item active px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="/"> @WebApplication4.Resources.lang.Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="/Uye/Giris">@WebApplication4.Resources.lang.Login</a>
                </li>
                <li class="nav-item px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="/Kitaps/Kitaplar">@WebApplication4.Resources.lang.Books</a>
                </li>
                <li class="nav-item px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="/CalismaSaat">@WebApplication4.Resources.lang.CalismaSaatleri</a>
                </li>
                <li class="nav-item px-lg-4">
                    <a class="nav-link text-uppercase text-expanded" href="~/Kitaps/Index">@WebApplication4.Resources.lang.UpdateBooks</a>
                </li>
            </ul>

            <ul class="navbar-nav pull-right">
                @if (Session["KullanıcıAdı"] != null)
                {
                    <li> @Html.ActionLink(@WebApplication4.Resources.lang.Exit, "Cikis", "Uye") </li>
                }
            </ul>
        </div>
    </div>
</nav>